//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM İlişkisi Meta Verileri

[assembly: EdmRelationshipAttribute("DBLMSModel", "FK_TBLBOOK_TBLAUTHOR", "TBLAUTHOR", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Graduation_Project.Models.Entity.TBLAUTHOR), "TBLBOOK", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Graduation_Project.Models.Entity.TBLBOOK), true)]
[assembly: EdmRelationshipAttribute("DBLMSModel", "FK_TBLBOOK_TBLCATEGORY", "TBLCATEGORY", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Graduation_Project.Models.Entity.TBLCATEGORY), "TBLBOOK", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Graduation_Project.Models.Entity.TBLBOOK), true)]
[assembly: EdmRelationshipAttribute("DBLMSModel", "FK_TBLMOVEMENT_TBLBOOK", "TBLBOOK", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Graduation_Project.Models.Entity.TBLBOOK), "TBLMOVEMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Graduation_Project.Models.Entity.TBLMOVEMENT), true)]
[assembly: EdmRelationshipAttribute("DBLMSModel", "FK_TBLMOVEMENT_TBLUSERS", "TBLUSERS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Graduation_Project.Models.Entity.TBLUSERS), "TBLMOVEMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Graduation_Project.Models.Entity.TBLMOVEMENT), true)]
[assembly: EdmRelationshipAttribute("DBLMSModel", "FK_TBLPENALTY_TBLMOVEMENT", "TBLMOVEMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Graduation_Project.Models.Entity.TBLMOVEMENT), "TBLPENALTY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Graduation_Project.Models.Entity.TBLPENALTY), true)]
[assembly: EdmRelationshipAttribute("DBLMSModel", "FK_TBLPENALTY_TBLUSERS", "TBLUSERS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Graduation_Project.Models.Entity.TBLUSERS), "TBLPENALTY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Graduation_Project.Models.Entity.TBLPENALTY), true)]

#endregion

namespace Graduation_Project.Models.Entity
{
    #region Bağlamlar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    public partial class DBLMSEntities : ObjectContext
    {
        #region Oluşturucular
    
        /// <summary>
        /// Yeni DBLMSEntities nesnesini, uygulama yapılandırma dosyasının 'DBLMSEntities' bölümünde bulunan bağlantı dizesini kullanarak başlatır.
        /// </summary>
        public DBLMSEntities() : base("name=DBLMSEntities", "DBLMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir DBLMSEntities nesnesi başlatın.
        /// </summary>
        public DBLMSEntities(string connectionString) : base(connectionString, "DBLMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir DBLMSEntities nesnesi başlatın.
        /// </summary>
        public DBLMSEntities(EntityConnection connection) : base(connection, "DBLMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Kısmi Metotlar
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLAUTHOR> TBLAUTHOR
        {
            get
            {
                if ((_TBLAUTHOR == null))
                {
                    _TBLAUTHOR = base.CreateObjectSet<TBLAUTHOR>("TBLAUTHOR");
                }
                return _TBLAUTHOR;
            }
        }
        private ObjectSet<TBLAUTHOR> _TBLAUTHOR;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLBOOK> TBLBOOK
        {
            get
            {
                if ((_TBLBOOK == null))
                {
                    _TBLBOOK = base.CreateObjectSet<TBLBOOK>("TBLBOOK");
                }
                return _TBLBOOK;
            }
        }
        private ObjectSet<TBLBOOK> _TBLBOOK;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLCATEGORY> TBLCATEGORY
        {
            get
            {
                if ((_TBLCATEGORY == null))
                {
                    _TBLCATEGORY = base.CreateObjectSet<TBLCATEGORY>("TBLCATEGORY");
                }
                return _TBLCATEGORY;
            }
        }
        private ObjectSet<TBLCATEGORY> _TBLCATEGORY;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLMOVEMENT> TBLMOVEMENT
        {
            get
            {
                if ((_TBLMOVEMENT == null))
                {
                    _TBLMOVEMENT = base.CreateObjectSet<TBLMOVEMENT>("TBLMOVEMENT");
                }
                return _TBLMOVEMENT;
            }
        }
        private ObjectSet<TBLMOVEMENT> _TBLMOVEMENT;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLPENALTY> TBLPENALTY
        {
            get
            {
                if ((_TBLPENALTY == null))
                {
                    _TBLPENALTY = base.CreateObjectSet<TBLPENALTY>("TBLPENALTY");
                }
                return _TBLPENALTY;
            }
        }
        private ObjectSet<TBLPENALTY> _TBLPENALTY;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLSTAFF> TBLSTAFF
        {
            get
            {
                if ((_TBLSTAFF == null))
                {
                    _TBLSTAFF = base.CreateObjectSet<TBLSTAFF>("TBLSTAFF");
                }
                return _TBLSTAFF;
            }
        }
        private ObjectSet<TBLSTAFF> _TBLSTAFF;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBLUSERS> TBLUSERS
        {
            get
            {
                if ((_TBLUSERS == null))
                {
                    _TBLUSERS = base.CreateObjectSet<TBLUSERS>("TBLUSERS");
                }
                return _TBLUSERS;
            }
        }
        private ObjectSet<TBLUSERS> _TBLUSERS;

        #endregion

        #region AddTo Metotları
    
        /// <summary>
        /// sysdiagrams EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// TBLAUTHOR EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLAUTHOR(TBLAUTHOR tBLAUTHOR)
        {
            base.AddObject("TBLAUTHOR", tBLAUTHOR);
        }
    
        /// <summary>
        /// TBLBOOK EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLBOOK(TBLBOOK tBLBOOK)
        {
            base.AddObject("TBLBOOK", tBLBOOK);
        }
    
        /// <summary>
        /// TBLCATEGORY EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLCATEGORY(TBLCATEGORY tBLCATEGORY)
        {
            base.AddObject("TBLCATEGORY", tBLCATEGORY);
        }
    
        /// <summary>
        /// TBLMOVEMENT EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLMOVEMENT(TBLMOVEMENT tBLMOVEMENT)
        {
            base.AddObject("TBLMOVEMENT", tBLMOVEMENT);
        }
    
        /// <summary>
        /// TBLPENALTY EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLPENALTY(TBLPENALTY tBLPENALTY)
        {
            base.AddObject("TBLPENALTY", tBLPENALTY);
        }
    
        /// <summary>
        /// TBLSTAFF EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLSTAFF(TBLSTAFF tBLSTAFF)
        {
            base.AddObject("TBLSTAFF", tBLSTAFF);
        }
    
        /// <summary>
        /// TBLUSERS EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBLUSERS(TBLUSERS tBLUSERS)
        {
            base.AddObject("TBLUSERS", tBLUSERS);
        }

        #endregion

    }

    #endregion

    #region Varlıklar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir sysdiagrams nesnesi oluşturun.
        /// </summary>
        /// <param name="name">name özelliğinin ilk değeri.</param>
        /// <param name="principal_id">principal_id özelliğinin ilk değeri.</param>
        /// <param name="diagram_id">diagram_id özelliğinin ilk değeri.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLAUTHOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLAUTHOR : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLAUTHOR nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLAUTHOR CreateTBLAUTHOR(global::System.Int32 id)
        {
            TBLAUTHOR tBLAUTHOR = new TBLAUTHOR();
            tBLAUTHOR.ID = id;
            return tBLAUTHOR;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SURNAME
        {
            get
            {
                return _SURNAME;
            }
            set
            {
                OnSURNAMEChanging(value);
                ReportPropertyChanging("SURNAME");
                _SURNAME = StructuralObject.SetValidValue(value, true, "SURNAME");
                ReportPropertyChanged("SURNAME");
                OnSURNAMEChanged();
            }
        }
        private global::System.String _SURNAME;
        partial void OnSURNAMEChanging(global::System.String value);
        partial void OnSURNAMEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DETAILS
        {
            get
            {
                return _DETAILS;
            }
            set
            {
                OnDETAILSChanging(value);
                ReportPropertyChanging("DETAILS");
                _DETAILS = StructuralObject.SetValidValue(value, true, "DETAILS");
                ReportPropertyChanged("DETAILS");
                OnDETAILSChanged();
            }
        }
        private global::System.String _DETAILS;
        partial void OnDETAILSChanging(global::System.String value);
        partial void OnDETAILSChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLBOOK_TBLAUTHOR", "TBLBOOK")]
        public EntityCollection<TBLBOOK> TBLBOOK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLBOOK>("DBLMSModel.FK_TBLBOOK_TBLAUTHOR", "TBLBOOK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLBOOK>("DBLMSModel.FK_TBLBOOK_TBLAUTHOR", "TBLBOOK", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLBOOK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLBOOK : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLBOOK nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLBOOK CreateTBLBOOK(global::System.Int32 id)
        {
            TBLBOOK tBLBOOK = new TBLBOOK();
            tBLBOOK.ID = id;
            return tBLBOOK;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> CATEGORY
        {
            get
            {
                return _CATEGORY;
            }
            set
            {
                OnCATEGORYChanging(value);
                ReportPropertyChanging("CATEGORY");
                _CATEGORY = StructuralObject.SetValidValue(value, "CATEGORY");
                ReportPropertyChanged("CATEGORY");
                OnCATEGORYChanged();
            }
        }
        private Nullable<global::System.Byte> _CATEGORY;
        partial void OnCATEGORYChanging(Nullable<global::System.Byte> value);
        partial void OnCATEGORYChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AUTHOR
        {
            get
            {
                return _AUTHOR;
            }
            set
            {
                OnAUTHORChanging(value);
                ReportPropertyChanging("AUTHOR");
                _AUTHOR = StructuralObject.SetValidValue(value, "AUTHOR");
                ReportPropertyChanged("AUTHOR");
                OnAUTHORChanged();
            }
        }
        private Nullable<global::System.Int32> _AUTHOR;
        partial void OnAUTHORChanging(Nullable<global::System.Int32> value);
        partial void OnAUTHORChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRINTEDYEAR
        {
            get
            {
                return _PRINTEDYEAR;
            }
            set
            {
                OnPRINTEDYEARChanging(value);
                ReportPropertyChanging("PRINTEDYEAR");
                _PRINTEDYEAR = StructuralObject.SetValidValue(value, true, "PRINTEDYEAR");
                ReportPropertyChanged("PRINTEDYEAR");
                OnPRINTEDYEARChanged();
            }
        }
        private global::System.String _PRINTEDYEAR;
        partial void OnPRINTEDYEARChanging(global::System.String value);
        partial void OnPRINTEDYEARChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PUBLISHER
        {
            get
            {
                return _PUBLISHER;
            }
            set
            {
                OnPUBLISHERChanging(value);
                ReportPropertyChanging("PUBLISHER");
                _PUBLISHER = StructuralObject.SetValidValue(value, true, "PUBLISHER");
                ReportPropertyChanged("PUBLISHER");
                OnPUBLISHERChanged();
            }
        }
        private global::System.String _PUBLISHER;
        partial void OnPUBLISHERChanging(global::System.String value);
        partial void OnPUBLISHERChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAGE
        {
            get
            {
                return _PAGE;
            }
            set
            {
                OnPAGEChanging(value);
                ReportPropertyChanging("PAGE");
                _PAGE = StructuralObject.SetValidValue(value, true, "PAGE");
                ReportPropertyChanged("PAGE");
                OnPAGEChanged();
            }
        }
        private global::System.String _PAGE;
        partial void OnPAGEChanging(global::System.String value);
        partial void OnPAGEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SITUATION
        {
            get
            {
                return _SITUATION;
            }
            set
            {
                OnSITUATIONChanging(value);
                ReportPropertyChanging("SITUATION");
                _SITUATION = StructuralObject.SetValidValue(value, "SITUATION");
                ReportPropertyChanged("SITUATION");
                OnSITUATIONChanged();
            }
        }
        private Nullable<global::System.Boolean> _SITUATION;
        partial void OnSITUATIONChanging(Nullable<global::System.Boolean> value);
        partial void OnSITUATIONChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLBOOK_TBLAUTHOR", "TBLAUTHOR")]
        public TBLAUTHOR TBLAUTHOR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLAUTHOR>("DBLMSModel.FK_TBLBOOK_TBLAUTHOR", "TBLAUTHOR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLAUTHOR>("DBLMSModel.FK_TBLBOOK_TBLAUTHOR", "TBLAUTHOR").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLAUTHOR> TBLAUTHORReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLAUTHOR>("DBLMSModel.FK_TBLBOOK_TBLAUTHOR", "TBLAUTHOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLAUTHOR>("DBLMSModel.FK_TBLBOOK_TBLAUTHOR", "TBLAUTHOR", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLBOOK_TBLCATEGORY", "TBLCATEGORY")]
        public TBLCATEGORY TBLCATEGORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLCATEGORY>("DBLMSModel.FK_TBLBOOK_TBLCATEGORY", "TBLCATEGORY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLCATEGORY>("DBLMSModel.FK_TBLBOOK_TBLCATEGORY", "TBLCATEGORY").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLCATEGORY> TBLCATEGORYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLCATEGORY>("DBLMSModel.FK_TBLBOOK_TBLCATEGORY", "TBLCATEGORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLCATEGORY>("DBLMSModel.FK_TBLBOOK_TBLCATEGORY", "TBLCATEGORY", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLMOVEMENT_TBLBOOK", "TBLMOVEMENT")]
        public EntityCollection<TBLMOVEMENT> TBLMOVEMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLMOVEMENT>("DBLMSModel.FK_TBLMOVEMENT_TBLBOOK", "TBLMOVEMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLMOVEMENT>("DBLMSModel.FK_TBLMOVEMENT_TBLBOOK", "TBLMOVEMENT", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLCATEGORY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLCATEGORY : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLCATEGORY nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLCATEGORY CreateTBLCATEGORY(global::System.Byte id)
        {
            TBLCATEGORY tBLCATEGORY = new TBLCATEGORY();
            tBLCATEGORY.ID = id;
            return tBLCATEGORY;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Byte _ID;
        partial void OnIDChanging(global::System.Byte value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLBOOK_TBLCATEGORY", "TBLBOOK")]
        public EntityCollection<TBLBOOK> TBLBOOK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLBOOK>("DBLMSModel.FK_TBLBOOK_TBLCATEGORY", "TBLBOOK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLBOOK>("DBLMSModel.FK_TBLBOOK_TBLCATEGORY", "TBLBOOK", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLMOVEMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLMOVEMENT : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLMOVEMENT nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLMOVEMENT CreateTBLMOVEMENT(global::System.Int32 id)
        {
            TBLMOVEMENT tBLMOVEMENT = new TBLMOVEMENT();
            tBLMOVEMENT.ID = id;
            return tBLMOVEMENT;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BOOK
        {
            get
            {
                return _BOOK;
            }
            set
            {
                OnBOOKChanging(value);
                ReportPropertyChanging("BOOK");
                _BOOK = StructuralObject.SetValidValue(value, "BOOK");
                ReportPropertyChanged("BOOK");
                OnBOOKChanged();
            }
        }
        private Nullable<global::System.Int32> _BOOK;
        partial void OnBOOKChanging(Nullable<global::System.Int32> value);
        partial void OnBOOKChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> USERS
        {
            get
            {
                return _USERS;
            }
            set
            {
                OnUSERSChanging(value);
                ReportPropertyChanging("USERS");
                _USERS = StructuralObject.SetValidValue(value, "USERS");
                ReportPropertyChanged("USERS");
                OnUSERSChanged();
            }
        }
        private Nullable<global::System.Int32> _USERS;
        partial void OnUSERSChanging(Nullable<global::System.Int32> value);
        partial void OnUSERSChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> STAFF
        {
            get
            {
                return _STAFF;
            }
            set
            {
                OnSTAFFChanging(value);
                ReportPropertyChanging("STAFF");
                _STAFF = StructuralObject.SetValidValue(value, "STAFF");
                ReportPropertyChanged("STAFF");
                OnSTAFFChanged();
            }
        }
        private Nullable<global::System.Int32> _STAFF;
        partial void OnSTAFFChanging(Nullable<global::System.Int32> value);
        partial void OnSTAFFChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PURCHASEDATE
        {
            get
            {
                return _PURCHASEDATE;
            }
            set
            {
                OnPURCHASEDATEChanging(value);
                ReportPropertyChanging("PURCHASEDATE");
                _PURCHASEDATE = StructuralObject.SetValidValue(value, "PURCHASEDATE");
                ReportPropertyChanged("PURCHASEDATE");
                OnPURCHASEDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _PURCHASEDATE;
        partial void OnPURCHASEDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnPURCHASEDATEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RETURNDATE
        {
            get
            {
                return _RETURNDATE;
            }
            set
            {
                OnRETURNDATEChanging(value);
                ReportPropertyChanging("RETURNDATE");
                _RETURNDATE = StructuralObject.SetValidValue(value, "RETURNDATE");
                ReportPropertyChanged("RETURNDATE");
                OnRETURNDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _RETURNDATE;
        partial void OnRETURNDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnRETURNDATEChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLMOVEMENT_TBLBOOK", "TBLBOOK")]
        public TBLBOOK TBLBOOK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLBOOK>("DBLMSModel.FK_TBLMOVEMENT_TBLBOOK", "TBLBOOK").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLBOOK>("DBLMSModel.FK_TBLMOVEMENT_TBLBOOK", "TBLBOOK").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLBOOK> TBLBOOKReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLBOOK>("DBLMSModel.FK_TBLMOVEMENT_TBLBOOK", "TBLBOOK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLBOOK>("DBLMSModel.FK_TBLMOVEMENT_TBLBOOK", "TBLBOOK", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLMOVEMENT_TBLUSERS", "TBLUSERS")]
        public TBLUSERS TBLUSERS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLMOVEMENT_TBLUSERS", "TBLUSERS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLMOVEMENT_TBLUSERS", "TBLUSERS").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLUSERS> TBLUSERSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLMOVEMENT_TBLUSERS", "TBLUSERS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLMOVEMENT_TBLUSERS", "TBLUSERS", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLPENALTY_TBLMOVEMENT", "TBLPENALTY")]
        public EntityCollection<TBLPENALTY> TBLPENALTY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLPENALTY>("DBLMSModel.FK_TBLPENALTY_TBLMOVEMENT", "TBLPENALTY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLPENALTY>("DBLMSModel.FK_TBLPENALTY_TBLMOVEMENT", "TBLPENALTY", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLPENALTY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLPENALTY : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLPENALTY nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLPENALTY CreateTBLPENALTY(global::System.Int32 id)
        {
            TBLPENALTY tBLPENALTY = new TBLPENALTY();
            tBLPENALTY.ID = id;
            return tBLPENALTY;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> USERS
        {
            get
            {
                return _USERS;
            }
            set
            {
                OnUSERSChanging(value);
                ReportPropertyChanging("USERS");
                _USERS = StructuralObject.SetValidValue(value, "USERS");
                ReportPropertyChanged("USERS");
                OnUSERSChanged();
            }
        }
        private Nullable<global::System.Int32> _USERS;
        partial void OnUSERSChanging(Nullable<global::System.Int32> value);
        partial void OnUSERSChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SITUATION
        {
            get
            {
                return _SITUATION;
            }
            set
            {
                OnSITUATIONChanging(value);
                ReportPropertyChanging("SITUATION");
                _SITUATION = StructuralObject.SetValidValue(value, "SITUATION");
                ReportPropertyChanged("SITUATION");
                OnSITUATIONChanged();
            }
        }
        private Nullable<global::System.Int32> _SITUATION;
        partial void OnSITUATIONChanging(Nullable<global::System.Int32> value);
        partial void OnSITUATIONChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> START
        {
            get
            {
                return _START;
            }
            set
            {
                OnSTARTChanging(value);
                ReportPropertyChanging("START");
                _START = StructuralObject.SetValidValue(value, "START");
                ReportPropertyChanged("START");
                OnSTARTChanged();
            }
        }
        private Nullable<global::System.DateTime> _START;
        partial void OnSTARTChanging(Nullable<global::System.DateTime> value);
        partial void OnSTARTChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FINISH
        {
            get
            {
                return _FINISH;
            }
            set
            {
                OnFINISHChanging(value);
                ReportPropertyChanging("FINISH");
                _FINISH = StructuralObject.SetValidValue(value, "FINISH");
                ReportPropertyChanged("FINISH");
                OnFINISHChanged();
            }
        }
        private Nullable<global::System.DateTime> _FINISH;
        partial void OnFINISHChanging(Nullable<global::System.DateTime> value);
        partial void OnFINISHChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONEY
        {
            get
            {
                return _MONEY;
            }
            set
            {
                OnMONEYChanging(value);
                ReportPropertyChanging("MONEY");
                _MONEY = StructuralObject.SetValidValue(value, "MONEY");
                ReportPropertyChanged("MONEY");
                OnMONEYChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONEY;
        partial void OnMONEYChanging(Nullable<global::System.Decimal> value);
        partial void OnMONEYChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLPENALTY_TBLMOVEMENT", "TBLMOVEMENT")]
        public TBLMOVEMENT TBLMOVEMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLMOVEMENT>("DBLMSModel.FK_TBLPENALTY_TBLMOVEMENT", "TBLMOVEMENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLMOVEMENT>("DBLMSModel.FK_TBLPENALTY_TBLMOVEMENT", "TBLMOVEMENT").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLMOVEMENT> TBLMOVEMENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLMOVEMENT>("DBLMSModel.FK_TBLPENALTY_TBLMOVEMENT", "TBLMOVEMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLMOVEMENT>("DBLMSModel.FK_TBLPENALTY_TBLMOVEMENT", "TBLMOVEMENT", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLPENALTY_TBLUSERS", "TBLUSERS")]
        public TBLUSERS TBLUSERS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLPENALTY_TBLUSERS", "TBLUSERS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLPENALTY_TBLUSERS", "TBLUSERS").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBLUSERS> TBLUSERSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLPENALTY_TBLUSERS", "TBLUSERS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBLUSERS>("DBLMSModel.FK_TBLPENALTY_TBLUSERS", "TBLUSERS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLSTAFF")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLSTAFF : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLSTAFF nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLSTAFF CreateTBLSTAFF(global::System.Byte id)
        {
            TBLSTAFF tBLSTAFF = new TBLSTAFF();
            tBLSTAFF.ID = id;
            return tBLSTAFF;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Byte _ID;
        partial void OnIDChanging(global::System.Byte value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STAFF
        {
            get
            {
                return _STAFF;
            }
            set
            {
                OnSTAFFChanging(value);
                ReportPropertyChanging("STAFF");
                _STAFF = StructuralObject.SetValidValue(value, true, "STAFF");
                ReportPropertyChanged("STAFF");
                OnSTAFFChanged();
            }
        }
        private global::System.String _STAFF;
        partial void OnSTAFFChanging(global::System.String value);
        partial void OnSTAFFChanged();

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBLMSModel", Name="TBLUSERS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLUSERS : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBLUSERS nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        public static TBLUSERS CreateTBLUSERS(global::System.Int32 id)
        {
            TBLUSERS tBLUSERS = new TBLUSERS();
            tBLUSERS.ID = id;
            return tBLUSERS;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SURNAME
        {
            get
            {
                return _SURNAME;
            }
            set
            {
                OnSURNAMEChanging(value);
                ReportPropertyChanging("SURNAME");
                _SURNAME = StructuralObject.SetValidValue(value, true, "SURNAME");
                ReportPropertyChanged("SURNAME");
                OnSURNAMEChanged();
            }
        }
        private global::System.String _SURNAME;
        partial void OnSURNAMEChanging(global::System.String value);
        partial void OnSURNAMEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAIL
        {
            get
            {
                return _MAIL;
            }
            set
            {
                OnMAILChanging(value);
                ReportPropertyChanging("MAIL");
                _MAIL = StructuralObject.SetValidValue(value, true, "MAIL");
                ReportPropertyChanged("MAIL");
                OnMAILChanged();
            }
        }
        private global::System.String _MAIL;
        partial void OnMAILChanging(global::System.String value);
        partial void OnMAILChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERNAME
        {
            get
            {
                return _USERNAME;
            }
            set
            {
                OnUSERNAMEChanging(value);
                ReportPropertyChanging("USERNAME");
                _USERNAME = StructuralObject.SetValidValue(value, true, "USERNAME");
                ReportPropertyChanged("USERNAME");
                OnUSERNAMEChanged();
            }
        }
        private global::System.String _USERNAME;
        partial void OnUSERNAMEChanging(global::System.String value);
        partial void OnUSERNAMEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, true, "PASSWORD");
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHOTO
        {
            get
            {
                return _PHOTO;
            }
            set
            {
                OnPHOTOChanging(value);
                ReportPropertyChanging("PHOTO");
                _PHOTO = StructuralObject.SetValidValue(value, true, "PHOTO");
                ReportPropertyChanged("PHOTO");
                OnPHOTOChanged();
            }
        }
        private global::System.String _PHOTO;
        partial void OnPHOTOChanging(global::System.String value);
        partial void OnPHOTOChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true, "PHONE");
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SCHOOL
        {
            get
            {
                return _SCHOOL;
            }
            set
            {
                OnSCHOOLChanging(value);
                ReportPropertyChanging("SCHOOL");
                _SCHOOL = StructuralObject.SetValidValue(value, true, "SCHOOL");
                ReportPropertyChanged("SCHOOL");
                OnSCHOOLChanged();
            }
        }
        private global::System.String _SCHOOL;
        partial void OnSCHOOLChanging(global::System.String value);
        partial void OnSCHOOLChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLMOVEMENT_TBLUSERS", "TBLMOVEMENT")]
        public EntityCollection<TBLMOVEMENT> TBLMOVEMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLMOVEMENT>("DBLMSModel.FK_TBLMOVEMENT_TBLUSERS", "TBLMOVEMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLMOVEMENT>("DBLMSModel.FK_TBLMOVEMENT_TBLUSERS", "TBLMOVEMENT", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBLMSModel", "FK_TBLPENALTY_TBLUSERS", "TBLPENALTY")]
        public EntityCollection<TBLPENALTY> TBLPENALTY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBLPENALTY>("DBLMSModel.FK_TBLPENALTY_TBLUSERS", "TBLPENALTY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBLPENALTY>("DBLMSModel.FK_TBLPENALTY_TBLUSERS", "TBLPENALTY", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
