//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMOVEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMOVEMENT()
        {
            this.TBLPENALTY = new HashSet<TBLPENALTY>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK { get; set; }
        public Nullable<int> USERS { get; set; }
        public Nullable<int> STAFF { get; set; }
        public Nullable<System.DateTime> PURCHASEDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
    
        public virtual TBLBOOK TBLBOOK { get; set; }
        public virtual TBLUSERS TBLUSERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPENALTY> TBLPENALTY { get; set; }
    }
}
