//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPENALTY
    {
        public int ID { get; set; }
        public Nullable<int> USERS { get; set; }
        public Nullable<int> SITUATION { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> FINISH { get; set; }
        public Nullable<decimal> MONEY { get; set; }
    
        public virtual TBLMOVEMENT TBLMOVEMENT { get; set; }
        public virtual TBLUSERS TBLUSERS { get; set; }
    }
}
